### PR TITLE
feat: Created page content placeholder component

### LINKED ISSUE #4: Implement Page Content Placeholder
### Context:
- Every page in the app consists of 3 parts - `Navbar`, `Collapsible Sidebar` and `Page Content`
- This issue will mainly focus on implementation of a substitutable placeholder for the `Page Content` such that we can easily fill this placeholder with the actual content (`Timetable`, `Module Details` or `Modules List`)
- Refer to [Figma](https://www.figma.com/file/KnUISVb48yTlFgMQLmfjAP/WAD2?node-id=13543%3A62165) for exact dimensions
image

### Tests and Passing Criteria
- Placeholder should be able to be replaced easily with another component OR it should take in a component to be rendered
- Basic responsiveness and breakpoints expected for small and large screens

### PR DESCRIPTION
**Pull request by jeromeandrewong**
1. created page content placeholder component that takes in another component to be displayed
2. changed sidebar to be fixed and span the whole length of screen
3. sidebar overlaps content when toggled on
4. created SampleContent component for sample content to test page content placeholder component

### CODE REVIEW

**Review by davidlhw — CHANGES_REQUESTED** [review]
Thanks for the PR!

Overall looks great but `PageContentPlaceholder` seems to be behind the sidebar when the sidebar is active instead of being beside the sidebar. Refer to this screenshot:

<p align="center">

</p>

**Comment by jeromeandrewong** [comment]
@DavidLHW Actually that was intended, do u think we the sidebar should displace the contents to the right instead?

**Comment by davidlhw** [comment]
> @DavidLHW Actually that was intended, do u think we the sidebar should displace the contents to the right instead?

I see, thanks for clarifying! It's not a big issue but just thought that it's not ideal to have the user perform 2 clicks to navigate to other pages.

Looking through at Jira's & Notion's version of the sidebar, they both exhibit similar behaviors:
1. Toggle is an intentional action
2. Content is beside the sidebar (unless Temporary View is triggered then the content will be behind the sidebar)
3. Hover to trigger Temporary View of the sidebar (user's cursor slides to the left border of the window to temporarily reveal sidebar for quick navigation)

Your implemenation is alright but I personally prefer Jira's & Notion's implementation as it minimizes the number of deliberate action from the user. Wdyt?

**Comment by davidlhw** [comment]
@jeromeandrewong I'll be merge this PR since it closes #4. CLGTM @ [a34d2bc](https://github.com/SMU-IS216G6T10/smumods-frontend/pull/12/commits/a34d2bc3f74d704e5ec4047e39f66b4cb99937db)

sidebar behavior is addressed with #14.

**Pull request merged**
